// SPDX-License-Identifier: AGPL-3.0-only
// Piece legibility (§B19 item 1): Black/White sprites carry wide transparent margins. This measures each board
// sprite's opaque bounding box (across every frame of an animated GIF, plus a 1 px margin) and writes the boxes to
// src/data/trim.json. The board then crops and scales each sprite with CSS, so animation is kept and no Nintendo art
// is re-encoded or committed: only numbers. Run after `npm run assets`: node scripts/trim-sprites.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import omggif from 'omggif';
import pngjs from 'pngjs';

const ROOT = 'public/assets';
const SETS = { front: 'gif', 'shiny/front': 'gif', 'static/front': 'png', 'static/shiny': 'png' };

function box(width, height, alphaAt) {
  let x0 = width, y0 = height, x1 = -1, y1 = -1;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      if (alphaAt(x, y) > 16) {
        if (x < x0) x0 = x;
        if (x > x1) x1 = x;
        if (y < y0) y0 = y;
        if (y > y1) y1 = y;
      }
    }
  }
  return { x0, y0, x1, y1 };
}

function gifBox(buf) {
  const g = new omggif.GifReader(new Uint8Array(buf));
  const W = g.width, H = g.height;
  let u = { x0: W, y0: H, x1: -1, y1: -1 };
  const pixels = new Uint8Array(W * H * 4);
  for (let f = 0; f < g.numFrames(); f++) {
    g.decodeAndBlitFrameRGBA(f, pixels);
    const b = box(W, H, (x, y) => pixels[(y * W + x) * 4 + 3]);
    u = { x0: Math.min(u.x0, b.x0), y0: Math.min(u.y0, b.y0), x1: Math.max(u.x1, b.x1), y1: Math.max(u.y1, b.y1) };
  }
  return { W, H, ...u };
}

function pngBox(buf) {
  const png = pngjs.PNG.sync.read(buf);
  return { W: png.width, H: png.height, ...box(png.width, png.height, (x, y) => png.data[(y * png.width + x) * 4 + 3]) };
}

const out = { _source: 'Opaque bounding boxes of the board sprites, 1 px margin: [x, y, w, h, W, H]. Generated by scripts/trim-sprites.mjs.' };
for (const [set, kind] of Object.entries(SETS)) {
  const dir = join(ROOT, set);
  const boxes = {};
  for (const f of readdirSync(dir).filter((n) => n.endsWith(`.${kind}`))) {
    const b = kind === 'gif' ? gifBox(readFileSync(join(dir, f))) : pngBox(readFileSync(join(dir, f)));
    if (b.x1 < 0) continue;
    const x = Math.max(0, b.x0 - 1), y = Math.max(0, b.y0 - 1);
    const w = Math.min(b.W, b.x1 + 2) - x, h = Math.min(b.H, b.y1 + 2) - y;
    boxes[f.split('.')[0]] = [x, y, w, h, b.W, b.H];
  }
  out[set] = boxes;
  console.log(`${set}: ${Object.keys(boxes).length} sprites measured`);
}
writeFileSync('src/data/trim.json', JSON.stringify(out) + '\n');
